// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/devchallenge/article-similarity/internal/http/models"
)

// GetArticlesOKCode is the HTTP code returned for type GetArticlesOK
const GetArticlesOKCode int = 200

/*GetArticlesOK OK.

swagger:response getArticlesOK
*/
type GetArticlesOK struct {

	/*
	  In: Body
	*/
	Payload *GetArticlesOKBody `json:"body,omitempty"`
}

// NewGetArticlesOK creates GetArticlesOK with default headers values
func NewGetArticlesOK() *GetArticlesOK {

	return &GetArticlesOK{}
}

// WithPayload adds the payload to the get articles o k response
func (o *GetArticlesOK) WithPayload(payload *GetArticlesOKBody) *GetArticlesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles o k response
func (o *GetArticlesOK) SetPayload(payload *GetArticlesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArticlesInternalServerErrorCode is the HTTP code returned for type GetArticlesInternalServerError
const GetArticlesInternalServerErrorCode int = 500

/*GetArticlesInternalServerError Internal server error

swagger:response getArticlesInternalServerError
*/
type GetArticlesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetArticlesInternalServerError creates GetArticlesInternalServerError with default headers values
func NewGetArticlesInternalServerError() *GetArticlesInternalServerError {

	return &GetArticlesInternalServerError{}
}

// WithPayload adds the payload to the get articles internal server error response
func (o *GetArticlesInternalServerError) WithPayload(payload *models.Error) *GetArticlesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles internal server error response
func (o *GetArticlesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
