// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/devchallenge/article-similarity/internal/http/models"
)

// GetArticlesHandlerFunc turns a function with the right signature into a get articles handler
type GetArticlesHandlerFunc func(GetArticlesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetArticlesHandlerFunc) Handle(params GetArticlesParams) middleware.Responder {
	return fn(params)
}

// GetArticlesHandler interface for that can handle valid get articles params
type GetArticlesHandler interface {
	Handle(GetArticlesParams) middleware.Responder
}

// NewGetArticles creates a new http.Handler for the get articles operation
func NewGetArticles(ctx *middleware.Context, handler GetArticlesHandler) *GetArticles {
	return &GetArticles{Context: ctx, Handler: handler}
}

/*GetArticles swagger:route GET /articles getArticles

Get unique articles.

*/
type GetArticles struct {
	Context *middleware.Context
	Handler GetArticlesHandler
}

func (o *GetArticles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetArticlesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetArticlesOKBody get articles o k body
//
// swagger:model GetArticlesOKBody
type GetArticlesOKBody struct {

	// articles
	// Required: true
	Articles []*models.Article `json:"articles"`
}

// Validate validates this get articles o k body
func (o *GetArticlesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateArticles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetArticlesOKBody) validateArticles(formats strfmt.Registry) error {

	if err := validate.Required("getArticlesOK"+"."+"articles", "body", o.Articles); err != nil {
		return err
	}

	for i := 0; i < len(o.Articles); i++ {
		if swag.IsZero(o.Articles[i]) { // not required
			continue
		}

		if o.Articles[i] != nil {
			if err := o.Articles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getArticlesOK" + "." + "articles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetArticlesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetArticlesOKBody) UnmarshalBinary(b []byte) error {
	var res GetArticlesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
