version: "3.8"
services:
  article-similarity:
    build: .
    image: article-similarity
    ports:
      - "80:80"
    environment:
      PORT: 80
      MONGO_HOST: mongo
      MONGO_PORT: 27017
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
