version: "3.8"
services:
  article-similarity:
    build: .
    image: article-similarity
    ports:
      - "80:80"
    environment:
      MONGO_HOST: mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
