// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/devchallenge/article-similarity/internal/models"
)

// GetArticlesIDOKCode is the HTTP code returned for type GetArticlesIDOK
const GetArticlesIDOKCode int = 200

/*GetArticlesIDOK OK

swagger:response getArticlesIdOK
*/
type GetArticlesIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Article `json:"body,omitempty"`
}

// NewGetArticlesIDOK creates GetArticlesIDOK with default headers values
func NewGetArticlesIDOK() *GetArticlesIDOK {

	return &GetArticlesIDOK{}
}

// WithPayload adds the payload to the get articles Id o k response
func (o *GetArticlesIDOK) WithPayload(payload *models.Article) *GetArticlesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles Id o k response
func (o *GetArticlesIDOK) SetPayload(payload *models.Article) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArticlesIDBadRequestCode is the HTTP code returned for type GetArticlesIDBadRequest
const GetArticlesIDBadRequestCode int = 400

/*GetArticlesIDBadRequest Invalid arguments

swagger:response getArticlesIdBadRequest
*/
type GetArticlesIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetArticlesIDBadRequest creates GetArticlesIDBadRequest with default headers values
func NewGetArticlesIDBadRequest() *GetArticlesIDBadRequest {

	return &GetArticlesIDBadRequest{}
}

// WithPayload adds the payload to the get articles Id bad request response
func (o *GetArticlesIDBadRequest) WithPayload(payload *models.Error) *GetArticlesIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles Id bad request response
func (o *GetArticlesIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArticlesIDNotFoundCode is the HTTP code returned for type GetArticlesIDNotFound
const GetArticlesIDNotFoundCode int = 404

/*GetArticlesIDNotFound Article not found

swagger:response getArticlesIdNotFound
*/
type GetArticlesIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetArticlesIDNotFound creates GetArticlesIDNotFound with default headers values
func NewGetArticlesIDNotFound() *GetArticlesIDNotFound {

	return &GetArticlesIDNotFound{}
}

// WithPayload adds the payload to the get articles Id not found response
func (o *GetArticlesIDNotFound) WithPayload(payload *models.Error) *GetArticlesIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles Id not found response
func (o *GetArticlesIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetArticlesIDInternalServerErrorCode is the HTTP code returned for type GetArticlesIDInternalServerError
const GetArticlesIDInternalServerErrorCode int = 500

/*GetArticlesIDInternalServerError Internal server error

swagger:response getArticlesIdInternalServerError
*/
type GetArticlesIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetArticlesIDInternalServerError creates GetArticlesIDInternalServerError with default headers values
func NewGetArticlesIDInternalServerError() *GetArticlesIDInternalServerError {

	return &GetArticlesIDInternalServerError{}
}

// WithPayload adds the payload to the get articles Id internal server error response
func (o *GetArticlesIDInternalServerError) WithPayload(payload *models.Error) *GetArticlesIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles Id internal server error response
func (o *GetArticlesIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
