// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetArticlesIDHandlerFunc turns a function with the right signature into a get articles ID handler
type GetArticlesIDHandlerFunc func(GetArticlesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetArticlesIDHandlerFunc) Handle(params GetArticlesIDParams) middleware.Responder {
	return fn(params)
}

// GetArticlesIDHandler interface for that can handle valid get articles ID params
type GetArticlesIDHandler interface {
	Handle(GetArticlesIDParams) middleware.Responder
}

// NewGetArticlesID creates a new http.Handler for the get articles ID operation
func NewGetArticlesID(ctx *middleware.Context, handler GetArticlesIDHandler) *GetArticlesID {
	return &GetArticlesID{Context: ctx, Handler: handler}
}

/*GetArticlesID swagger:route GET /articles/{id} getArticlesId

Get article by id.

*/
type GetArticlesID struct {
	Context *middleware.Context
	Handler GetArticlesIDHandler
}

func (o *GetArticlesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetArticlesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
