// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostArticlesOKCode is the HTTP code returned for type PostArticlesOK
const PostArticlesOKCode int = 200

/*PostArticlesOK OK

swagger:response postArticlesOK
*/
type PostArticlesOK struct {
}

// NewPostArticlesOK creates PostArticlesOK with default headers values
func NewPostArticlesOK() *PostArticlesOK {

	return &PostArticlesOK{}
}

// WriteResponse to the client
func (o *PostArticlesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
