// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ArticleID Article id
//
// swagger:model ArticleId
type ArticleID int64

// Validate validates this article Id
func (m ArticleID) Validate(formats strfmt.Registry) error {
	return nil
}
