// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Server to store articles and search similar articles",
    "title": "Article similarity",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/articles": {
      "post": {
        "summary": "Add an article",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "content"
              ],
              "properties": {
                "content": {
                  "description": "Article content",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ArticleOk"
          },
          "400": {
            "$ref": "#/responses/InvalidArgument"
          },
          "500": {
            "$ref": "#/responses/ServerError"
          }
        }
      }
    },
    "/articles/{id}": {
      "get": {
        "summary": "Get article by id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Article id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ArticleOk"
          },
          "400": {
            "$ref": "#/responses/InvalidArgument"
          },
          "404": {
            "description": "Article not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "$ref": "#/responses/ServerError"
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "ArticleOk": {
      "description": "OK",
      "schema": {
        "type": "object",
        "required": [
          "id",
          "content",
          "duplicate_article_ids"
        ],
        "properties": {
          "content": {
            "description": "Article content",
            "type": "string"
          },
          "duplicate_article_ids": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "id": {
            "description": "Article id",
            "type": "integer",
            "format": "int64"
          }
        }
      }
    },
    "InvalidArgument": {
      "description": "Invalid arguments",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "ServerError": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Server to store articles and search similar articles",
    "title": "Article similarity",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/articles": {
      "post": {
        "summary": "Add an article",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "content"
              ],
              "properties": {
                "content": {
                  "description": "Article content",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "id",
                "content",
                "duplicate_article_ids"
              ],
              "properties": {
                "content": {
                  "description": "Article content",
                  "type": "string"
                },
                "duplicate_article_ids": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  }
                },
                "id": {
                  "description": "Article id",
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Invalid arguments",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/articles/{id}": {
      "get": {
        "summary": "Get article by id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Article id",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "id",
                "content",
                "duplicate_article_ids"
              ],
              "properties": {
                "content": {
                  "description": "Article content",
                  "type": "string"
                },
                "duplicate_article_ids": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  }
                },
                "id": {
                  "description": "Article id",
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Invalid arguments",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Article not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "ArticleOk": {
      "description": "OK",
      "schema": {
        "type": "object",
        "required": [
          "id",
          "content",
          "duplicate_article_ids"
        ],
        "properties": {
          "content": {
            "description": "Article content",
            "type": "string"
          },
          "duplicate_article_ids": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "id": {
            "description": "Article id",
            "type": "integer",
            "format": "int64"
          }
        }
      }
    },
    "InvalidArgument": {
      "description": "Invalid arguments",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "ServerError": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  }
}`))
}
