// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Server to store articles and search similar articles",
    "title": "Article similarity API",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/articles": {
      "post": {
        "summary": "Add an article",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Server to store articles and search similar articles",
    "title": "Article similarity API",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/articles": {
      "post": {
        "summary": "Add an article",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
}
