// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/devchallenge/article-similarity/internal/swagger/models"
)

// GetDuplicateGroupsOKCode is the HTTP code returned for type GetDuplicateGroupsOK
const GetDuplicateGroupsOKCode int = 200

/*GetDuplicateGroupsOK OK.

swagger:response getDuplicateGroupsOK
*/
type GetDuplicateGroupsOK struct {

	/*
	  In: Body
	*/
	Payload *GetDuplicateGroupsOKBody `json:"body,omitempty"`
}

// NewGetDuplicateGroupsOK creates GetDuplicateGroupsOK with default headers values
func NewGetDuplicateGroupsOK() *GetDuplicateGroupsOK {

	return &GetDuplicateGroupsOK{}
}

// WithPayload adds the payload to the get duplicate groups o k response
func (o *GetDuplicateGroupsOK) WithPayload(payload *GetDuplicateGroupsOKBody) *GetDuplicateGroupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get duplicate groups o k response
func (o *GetDuplicateGroupsOK) SetPayload(payload *GetDuplicateGroupsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDuplicateGroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDuplicateGroupsInternalServerErrorCode is the HTTP code returned for type GetDuplicateGroupsInternalServerError
const GetDuplicateGroupsInternalServerErrorCode int = 500

/*GetDuplicateGroupsInternalServerError Internal server error

swagger:response getDuplicateGroupsInternalServerError
*/
type GetDuplicateGroupsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetDuplicateGroupsInternalServerError creates GetDuplicateGroupsInternalServerError with default headers values
func NewGetDuplicateGroupsInternalServerError() *GetDuplicateGroupsInternalServerError {

	return &GetDuplicateGroupsInternalServerError{}
}

// WithPayload adds the payload to the get duplicate groups internal server error response
func (o *GetDuplicateGroupsInternalServerError) WithPayload(payload *models.Error) *GetDuplicateGroupsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get duplicate groups internal server error response
func (o *GetDuplicateGroupsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDuplicateGroupsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
