swagger: "2.0"
info:
  title: Article similarity
  version: "1.0.0"
  description: Server to store articles and search similar articles.
basePath: /
schemes:
  - http
consumes:
  - application/json

paths:
  /articles:
    post:
      summary: Add an article.
      parameters:
        - in: body
          name: body
          schema:
            type: object
            required:
              - content
            properties:
              content:
                description: Article content
                type: string
            example:
              content: "Hello, a world!"
          required: true
      responses:
        201:
          description: Article added.
          schema:
            $ref: "#/definitions/Article"
          examples:
            application/json:
              { "id": 1, "content": "...", "duplicate_article_ids": [2, 3] }
        400:
          $ref: "#/responses/InvalidArgument"
        500:
          $ref: "#/responses/ServerError"

    get:
      summary: Get unique articles.
      responses:
        200:
          description: OK.
          schema:
            type: object
            properties:
              articles:
                type: array
                items:
                  $ref: "#/definitions/Article"
            required:
              - articles
          examples:
            application/json:
              {
                "articles": [
                  { "id": 1, "content": "...", "duplicate_article_ids": [3, 5] },
                  { "id": 2, "content": "...", "duplicate_article_ids": [] },
                  { "id": 4, "content": "...", "duplicate_article_ids": [] }
                ]
              }
        500:
          $ref: "#/responses/ServerError"

  /articles/{id}:
    get:
      summary: Get article by id.
      parameters:
        - in: path
          name: id
          description: Article id
          type: integer
          format: int64
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Article"
          examples:
            application/json:
              { "id": 1, "content": "...", "duplicate_article_ids": [2, 3] }
        400:
          $ref: "#/responses/InvalidArgument"
        404:
          description: Article not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          $ref: "#/responses/ServerError"

  /duplicate_groups:
    get:
      summary: Get duplicate groups ids.
      responses:
        200:
          description: OK.
          schema:
            type: object
            properties:
              duplicate_groups:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/definitions/ArticleId"
            required:
              - duplicate_groups
          examples:
            application/json:
              {
                "duplicate_groups": [ [1, 3, 5], [7, 8] ]
              }
        500:
          $ref: "#/responses/ServerError"

definitions:
  Error:
    type: object
    properties:
      code:
        description: Error code for machine parsing
        type: integer
        format: int64
      message:
        description: Human-readable error message
        type: string
    example:
      code: 602
      message: body in body is required
    required:
      - message

  ArticleId:
    description: Article id
    type: integer
    format: int64
    example: 1

  Article:
    type: object
    properties:
      id:
        $ref: "#/definitions/ArticleId"
      content:
        description: Article content
        type: string
      duplicate_article_ids:
        description: Duplicated articles
        type: array
        items:
          type: integer
    example:
      id: 1
      content: "Hello, a world!"
      duplicate_article_ids: [3, 4]
    required:
      - id
      - content
      - duplicate_article_ids

responses:
  InvalidArgument:
    description: Invalid arguments
    schema:
      $ref: '#/definitions/Error'

  ServerError:
    description: Internal server error
    schema:
      $ref: "#/definitions/Error"
