swagger: "2.0"
info:
  title: Article similarity
  version: "1.0.0"
  description: Server to store articles and search similar articles.
basePath: /
schemes:
  - http
consumes:
  - application/json

paths:
  /articles:
    post:
      summary: Add an article.
      parameters:
        - in: body
          name: body
          schema:
            type: object
            required:
              - content
            properties:
              content:
                description: Article content
                type: string
          required: true
      responses:
        201:
          description: Article added.
          schema:
            $ref: "#/definitions/Article"
        400:
          $ref: "#/responses/InvalidArgument"
        500:
          $ref: "#/responses/ServerError"

    get:
      summary: Get unique articles.
      responses:
        200:
          description: OK.
          schema:
            type: object
            properties:
              articles:
                type: array
                items:
                  $ref: "#/definitions/Article"
            required:
              - articles
        500:
          $ref: "#/responses/ServerError"

  /articles/{id}:
    get:
      summary: Get article by id.
      parameters:
        - in: path
          name: id
          description: Article id
          type: integer
          format: int64
          required: true
      responses:
        200:
          $ref: "#/responses/ArticleOk"
        400:
          $ref: "#/responses/InvalidArgument"
        404:
          description: Article not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          $ref: "#/responses/ServerError"

  /duplicate_groups:
    get:
      summary: Get duplicate groups ids.
      responses:
        200:
          description: OK.
          schema:
            type: object
            properties:
              duplicate_groups:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/definitions/ArticleId"
            required:
              - duplicate_groups
        500:
          $ref: "#/responses/ServerError"

definitions:
  Error:
    type: object
    properties:
      code:
        description: Error code for machine parsing
        type: integer
        format: int64
      message:
        description: Human-readable error message
        type: string
    required:
      - message

  ArticleId:
    description: Article id
    type: integer
    format: int64

  Article:
    type: object
    properties:
      id:
        $ref: "#/definitions/ArticleId"
      content:
        description: Article content
        type: string
      duplicate_article_ids:
        description: Duplicated articles
        type: array
        items:
          type: integer
    required:
      - id
      - content
      - duplicate_article_ids

responses:
  ArticleOk:
    description: OK
    schema:
      $ref: "#/definitions/Article"

  InvalidArgument:
    description: Invalid arguments
    schema:
      $ref: '#/definitions/Error'

  ServerError:
    description: Internal server error
    schema:
      $ref: "#/definitions/Error"
