swagger: "2.0"
info:
  title: Article similarity API
  version: "1.0.0"
  description: Server to store articles and search similar articles
basePath: /
schemes:
  - http
consumes:
  - application/json

paths:
  /articles:
    post:
      summary: Add an article
      responses:
        200:
          description: OK